name: Linux Development Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libasound2-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev \
            zlib1g-dev \
            pkg-config

      - name: Install Raylib
        run: |
          git clone https://github.com/raysan5/raylib.git raylib
          cd raylib/src
          make PLATFORM=PLATFORM_DESKTOP
          sudo make install
          cd ../..

      - name: Get Raygui
        run: |
          git clone https://github.com/raysan5/raygui.git

      - name: Build Project
        run: make all

      - name: Create build directory
        run: mkdir -p build

      - name: Package
        run: |
          mkdir -p artifacts/carousel-linux-x86_64
          cp build/carousel artifacts/carousel-linux-x86_64/
          cd artifacts
          tar czf carousel-linux-x86_64.tar.gz carousel-linux-x86_64/

      - name: Generate date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Development Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-${{ steps.date.outputs.date }}
          name: Development Build ${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
          files: artifacts/carousel-linux-x86_64.tar.gz